### ISSUE TITLE
"Koneet kiertoon" page image gallery overflows text

### ISSUE THREAD

**Issue by Eldemarkki** [Testausserveri/testausserveri.fi#105]
![image](https://github.com/Testausserveri/testausserveri.fi/assets/38920928/52a6a08b-20aa-4271-977c-e43457bab2f1)

**Comment by ahnl** [comment]
Fixed in https://github.com/Testausserveri/testausserveri.fi/commit/664d05fe0eee728bc38d599c03cb7ef80bfda543.
