### ISSUE TITLE
Changing text

### ISSUE THREAD

**Issue by ahnl** [Testausserveri/testausserveri.fi#35]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/46541386/167252653-e0eeac3d-4f5f-445d-ba60-2a76b5f63a72.png">

Someone suggested that "Nettiyhteisö nuorille **hakkereille**" sounds alone a bit weird. Swapping the **hakkereille** word each few second to a different with a nice animation could be a neat fix:
- hakkereille
- koodareille
- Linux-velhoille
- radioamatööreille
- etc.

Here's a component we could use.
https://www.npmjs.com/package/react-text-transition

**Comment by developerfromjokela** [comment]
I think that wouldn't be hard to implement in react, without a use of another dependency :-)

**Comment by ahnl** [comment]
Easily, if someone has time to do it. 

Regardless, the dependencies are processed by webpack.

**Comment by Eldemarkki** [comment]
If dependencies are allowed, this seems to be perfect for the job: https://github.com/braposo/react-text-loop

Here's a small demo showing the new words with react-text-loop: https://codesandbox.io/s/react-text-loop-playground-forked-0o9fvm?file=/src/App.tsx

**Comment by ahnl** [comment]
> If dependencies are allowed, this seems to be perfect for the job: https://github.com/braposo/react-text-loop
> 
> Here's a small demo showing the new words with react-text-loop: https://codesandbox.io/s/react-text-loop-playground-forked-0o9fvm?file=/src/App.tsx

Thanks, I ended up using this.

Feel free guys to suggest more titles such as:

- hakkereille
- koodareille
- Linux-velhoille
- radioamatööreille
- etc.
