### ISSUE TITLE
Footer images are highlighted with inverted color

### ISSUE THREAD

**Issue by Eldemarkki** [Testausserveri/testausserveri.fi#37]
If you highlight everything on the page with Ctrl + A, everything should be highlighted with the same color (in my case, blue). However, currently the images in the footer are the inverse of that color (in my case red), because of the `filter: invert(1)` CSS declaration.

![image](https://user-images.githubusercontent.com/38920928/167258139-87e99699-5b1e-4409-961c-620c4fca613d.png)

**Comment by ahnl** [comment]
Interesting finding :D

A fix could be to change the colors in the SVG files or use some kind of CSS trick to change the SVG fill color.
