### ISSUE TITLE
metaRepoLink redirects to 404 page

### ISSUE THREAD

**Issue by walokra** [Testausserveri/testausserveri.fi#45]
Should this link `https://github.com/testausserveri` on index.html [line 118](https://github.com/Testausserveri/testausserveri.fi/blob/a3923c2a458586e6805cdac3a56b585e3f172067/index.html#L118) redirect to e.g. `https://github.com/testausserveri`?

**Comment by Chicken** [comment]
The link is to a private repo. Agreed, that it might be a little confusing for outsiders. Maybe it should just be removed or made public.

**Comment by ahnl** [comment]
Thank you for your issue.

It is indeed confusing to the outside visitors as the private repository it's pointing to is not accessible. The repository contains more detailed list of projects than the GitHub repository list, but some time back for some reason we didn't dare to publicise it.

For now I'll go with the fix @walokra suggested, it's good enough for now. We are currently working on [new site](https://coal.testausserveri.fi) and we are planning to have an improved project listing there.
