### ISSUE TITLE
Project data

### ISSUE THREAD

**Issue by ahnl** [Testausserveri/testausserveri.fi#47]
I'm currently working on the projects-page, but it would be useful if there would be some actual content ready to use.

If someone wants to help out and contribute, feel free to gather data of existing Testausserveri projects and document them. I suggest in plain files and markdown, and we'll later move it all to a database. This content would be used as a base for the projects-page.

[Documentation can be placed here (coal: docs/project)](https://github.com/Testausserveri/testausserveri.fi/tree/coal/docs/projects)

## Specification

- Project name
- Authors / main contributors
- Picture(s)
   - At least one good presentable picture. Will be shown on the projects-page for each project.
   - You can take example from [current website](https://testausserveri.fi). They can be screenshots if they are pretty enough.
   - Can also be a video.
- Short description
- Optionally a longer description
- Links: GitHub, website, etc.

**Comment by ahnl** [comment]
- [x] QR-pyörä
- [ ] https://soundcloud.com/testausserveri/folkboy-abitti-litty
- [x] Testaustime
   - I'd suggest to include sub-projects (discord-bot, vscode extension) under this
- [x] StegoSiili
- [x] Abitti OpenAccess
- [ ] Abitikku
- [ ] Torimies
- [ ] kaatis.party
- [x] Testauskoira-rs
- [ ] abitikku-versions
- [ ] SoulCaptcha
- [ ] testausserveri-id
- [ ] testausapis
- [x] ktpjs-docker
- [ ] koirameili
- [ ] aamulaskuri
- [ ] Apu-botti
- [ ] testauskameli
- [ ] Testauspizza
- [ ] Testauslehti
- [x] Koululaskuri
- [ ] Testaussegfault
- [ ] Antiupditti
- [x] volume-backup
- [ ] whosbeenhere
- [ ] benchmarks
- [ ] env-exampler
- [ ] Testausbrowser
- [ ] shittifier
- [x] testausxml
- [ ] Matikkaeditori.fi
- [ ] OpenWilma
- [x] Karhu

**Comment by Eldemarkki** [comment]
> I suggest in plain files and markdown, and we'll later move it all to a database.

Moving it to a database is a bad idea in my opinion, assuming you mean something like MySQL or MongoDB. Having it in markdown files makes editing and creating them easier. If they are in a database, people will have a hard time creating "pull requests" to edit something.

With Next.js you can read the contents of the markdown file and dynamically  create the page from that content: https://nextjs.org/blog/markdown

**Comment by ahnl** [comment]
Keeping them in a repository is an option as well. 

I think that if we use a database, users can edit their projects through *members site*. This would offer more options, like instant editing without pull requests, drag&drop to add media, find users to link their authorship, ...

**Comment by Esinko** [comment]
Indeed. I think I will be implementing the backend and storage for the backend of the members page. I'm planning on using MongoDB and Node.js, so as many people as possible can contribute. If someone else is interested, feel free to DM me and I'll give a few requests regarding the project architecture.

**Comment by DrVilepis** [comment]
If we really need to store something in a database for this, I think its wiser to use one of the more popular databases (mysql, postgresql, sqlite) since more people know them.

**Comment by ahnl** [comment]
> If we really need to store something in a database for this, I think its wiser to use one of the more popular databases (mysql, postgresql, sqlite) since more people know them.

I agree, MariaDB.

**Comment by kymppi** [comment]
> I think that if we use a database, users can edit their projects through _members site_. This would offer more options, like instant editing without pull requests, drag&drop to add media, find users to link their authorship, ...

Does it really have to be instantanius, i'm sure it can wait few hours + we get a history in git if we use repository method

**Comment by ahnl** [comment]
> > If we really need to store something in a database for this, I think its wiser to use one of the more popular databases (mysql, postgresql, sqlite) since more people know them.
> 
> I agree, MariaDB.

[Testausapis already works with the MongoDB](https://github.com/Testausserveri/testausapis/blob/c3278b71edf89fbf98d8399f344c0920f0766eef/docker-compose.yml#L18-L25), so seems like we'll stick to it.

I was looking into many-to-many relationships so we can connect e.g. projects to members and vice versa. [MongoDB's support for relations is basically referencing to other rows](https://www.bezkoder.com/mongodb-many-to-many-mongoose/), but I think it's just fine albeit it requires more individual queries.

**Comment by Esinko** [comment]
> > > If we really need to store something in a database for this, I think its wiser to use one of the more popular databases (mysql, postgresql, sqlite) since more people know them.
> > 
> > 
> > I agree, MariaDB.
> 
> [Testausapis already works with the MongoDB](https://github.com/Testausserveri/testausapis/blob/c3278b71edf89fbf98d8399f344c0920f0766eef/docker-compose.yml#L18-L25), so seems like we'll stick to it.
> 
> I was looking into many-to-many relationships so we can connect e.g. projects to members and vice versa. [MongoDB's support for relations is basically referencing to other rows](https://www.bezkoder.com/mongodb-many-to-many-mongoose/), but I think it's just fine albeit it requires more individual queries.

This is why I suggested MongoDB in the first place :p
