### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by DrVilepis** [Testausserveri/testausserveri.fi#70]
> Pull requests are welcome. For major changes, please first either: ...

Contributions are encouraged, but the code is licensed under cc, which means it is a license infringement to modify the code and share it.
This should be fixed asap.

**Comment by ahnl** [comment]
@Esinko and I just decided to license the main branch with the MIT license. Feel free to open a pull request to commit the LICENSE file.

**Comment by ahnl** [comment]
Resolved in b4b1a027197b5c15d1051e31a713b3f68e8a0682
