### ISSUE TITLE
Dublicate lock files

### ISSUE THREAD

**Issue by KasperiP** [Testausserveri/testausserveri.fi#82]
Is this project using npm or yarn. Dublicate lock files not needed?

![image](https://user-images.githubusercontent.com/26027985/211778433-8638b3a6-0d73-4338-a3e8-0ca4a400b9e6.png)

**Comment by Esinko** [comment]
I believe the `yarn.lock` is not a duplicate. This project uses NPM and from my understanding, NPM generates the `yarn.lock` file to manage the dependices of dependencies that use Yarn, but are installed with NPM.

However, I'm not 100% sure, so if someone could provide more insight on this, that would be greatly appriciated.

**Comment by Chicken** [comment]
If NPM is used, `yarn.lock` should be removed. NPM does not generate it.

**Comment by Esinko** [comment]
> If NPM is used, `yarn.lock` should be removed. NPM does not generate it.

The NPM docs state that (about install):
```
This command installs a package and any packages that it depends on. If the package has a package-lock, or an npm shrinkwrap file, or a yarn lock file, the installation of dependencies will be driven by that, respecting the following order of precedence:

- npm-shrinkwrap.json
- package-lock.json
- yarn.lock
```
Doesn't this mean that if a package only has a `yarn.lock` NPM will use and create that?

**Comment by Chicken** [comment]
This only means NPM supports yarn's lockfiles for resolving dependencies if they exists but it won't generate any on it's own

**Comment by Esinko** [comment]
In that case `yarn.lock` shall be removed. Anyone can get on that.

**Comment by bluelhf** [comment]
> > If NPM is used, `yarn.lock` should be removed. NPM does not generate it.
> 
> The NPM docs state that (about install):
> ```
> This command installs a package and any packages that it depends on. If the package has a package-lock, or an npm shrinkwrap file, or a yarn lock file, the installation of dependencies will be driven by that, respecting the following order of precedence:
> 
> - npm-shrinkwrap.json
> - package-lock.json
> - yarn.lock
> ```
> Doesn't this mean that if a package only has a `yarn.lock` NPM will use and create that?

Presumably that'd be used only for _resolving_ dependencies and not created in the source package?
